### ISSUE TITLE
Daylight savings bug

### ISSUE THREAD

**Issue by BrendanSimon** [crsmithdev/arrow#315]
I have an embedded system which has no  Real Time Clock, running Debian Jessie.  On boot the time defaults to 1-Jan-1970 UTC.  I am using `chrony` to syncrhonise the system time with NTP servers.

My data logging app is running as a daemon (via `systemd`) and waits for the time to sync before logging (checks system time is > 2015).  Both UTC and Local Time are logged and the Local Time is reporting **AEST (Australian Eastern STANDARD Time)** instead of **AEDT (Australian Eastern DAYLIGHT-SAVINGS Time)**.

If I type `date` it reports the correct local time (AEDT).  If if run a python shell and run `arrow.now()` it reports the correct local time (AEDT).  If I restart my app (after network time is synced) then the app logs the correct local time (AEDT).

**Is this a bug in arrow (v0.4.4) ?**

One possible work around for me is to not start the app until network time is synchronised, but I'm not confident that arrow will report the correct local time after daylight savings ends.

Thanks for any help to solve this issue.
Brendan.

**Comment by BrendanSimon** [comment]
BUMP.  Anyone know why arrow can read the system date/time ok after it is updated via NTP, but doesn't read the Daylight Savings status after the NTP update ???

**Comment by pganssle** [comment]
@BrendanSimon I suspect that this issue is due dateutil/dateutil#100, which was fixed in `dateutil` version 2.5.0. Can you check if your dateutil version is <=2.4.2? If so, try upgrading to 2.5.0, it will probably fix your issue.

**Comment by BrendanSimon** [comment]
Looks like Debian does not have `dateutil` v2.5.0 in their distros yet :(

Jessie (stable) has 2.2 and Stretch (testing) and Sid (unstable) has 2.4.2.

[Debian `dateutil` packages](https://packages.debian.org/search?keywords=python-dateutil&searchon=names&suite=all&section=all)

**Comment by pganssle** [comment]
@BrendanSimon You should be able to just install it with `pip install --upgrade python-dateutil`. Otherwise, you can get it directly from [PyPi](https://pypi.python.org/pypi/python-dateutil/2.5.1) and build it from source (either by `python setup.py install` or just by [embedding it in your library](https://stackoverflow.com/questions/18812614/embedding-a-python-library-in-my-own-package) if for some reason you don't want to upgrade it on the machine as a whole).

**Comment by BrendanSimon** [comment]
Ok, so I installed `python-dateutil` with `pip install --ignore-installed python-dateutil==2.5.2` and it didn't seem to fix the issue.

**Any other ideas ??**

The output of the log file below is comma separated, with first field UTC time, second field is local time.

You can see that the only time the local time zone is updated (from `-09:00`to `-08:00`), is **after** I restart the application service (efd).

```
# python -c "import arrow; import dateutil; print(arrow.__version__, dateutil.__version__)"
('0.4.3', '2.5.2')

# cat /etc/timezone 
America/Adak

# tail -1 /mnt/data/log/measurements/measurements-20160405T000000-0000.csv 
2016-04-05 04:29:36+00:00,2016-04-04 19:29:36-09:00,-1.25,

# dpkg-reconfigure tzdata
Current default time zone: 'America/Anchorage'
Local time is now:      Mon Apr  4 20:29:51 AKDT 2016.
Universal Time is now:  Tue Apr  5 04:29:51 UTC 2016.

# cat /etc/timezone 
America/Anchorage

# tail -1 /mnt/data/log/measurements/measurements-20160405T000000-0000.csv 
2016-04-05 04:30:00+00:00,2016-04-04 19:30:00-09:00,-1.25,

# systemctl restart efd

# tail -1 /mnt/data/log/measurements/measurements-20160405T000000-0000.csv 
2016-04-05 04:30:06+00:00,2016-04-04 20:30:06-08:00,-1.25,
```

**Comment by BrendanSimon** [comment]
Upgrading `arrow` to the latest version (`0.7.0`) did not fix the issue either :(
